### ISSUE TITLE
locate_objects and visual_qa

### ISSUE THREAD

**Issue by longryan2024** [zorazrw/trove#1]
Hello, thanks for your great work! I wonder how you implemented locate_objects and visual_qa?

**Comment by zorazrw** [comment]
Hi, thanks for your interest and reminder! I just uploaded the gqa primitive implementation in `./server', and you should be able to use it follow the instruction here: [https://github.com/zorazrw/trove/blob/7aadd05e7c125f4f0c98254965ccb441adec1997/README.md?plain=1#L48](https://github.com/zorazrw/trove/blob/7aadd05e7c125f4f0c98254965ccb441adec1997/README.md?plain=1#L48)
